# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: addons.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x61\x64\x64ons.proto\x12\x0b\x63omputantis\",\n\rAddonsMessage\x12\r\n\x05token\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"\x1c\n\x0b\x41\x64\x64onsError\x12\r\n\x05\x65rror\x18\x01 \x01(\t2Y\n\tAddonsAPI\x12L\n\x12\x41nalyzeTransaction\x12\x1a.computantis.AddonsMessage\x1a\x18.computantis.AddonsError\"\x00\x42\x36Z4github.com/bartossh/Computantis/src/protobufcompiledb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'addons_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z4github.com/bartossh/Computantis/src/protobufcompiled'
  _globals['_ADDONSMESSAGE']._serialized_start=29
  _globals['_ADDONSMESSAGE']._serialized_end=73
  _globals['_ADDONSERROR']._serialized_start=75
  _globals['_ADDONSERROR']._serialized_end=103
  _globals['_ADDONSAPI']._serialized_start=105
  _globals['_ADDONSAPI']._serialized_end=194
# @@protoc_insertion_point(module_scope)
