// I am here only to allow the documentation to be generated by gomarkdoc

// Stress is a package that provides a simple way to stress test your code
// on the full cycle of transaction processing.
package stress
