FROM golang:latest as base_publisher
WORKDIR /app
COPY . .
RUN go mod tidy
RUN CGO_ENABLED=0 go build -a -installsuffix cgo -o emulator -ldflags="-s -w" cmd/emulator/main.go

FROM alpine:latest
RUN apk --no-cache add ca-certificates
WORKDIR /
COPY --from=base_publisher /app/emulator ./
COPY --from=base_publisher /app/setup.yaml ./
COPY --from=base_publisher /app/minmax.json ./

ENTRYPOINT [ "./emulator", "--config", "/setup.yaml", "--data", "minmax.json", "publisher"]
