FROM golang:latest as base_client
WORKDIR /app
COPY . .
RUN go mod tidy
RUN CGO_ENABLED=0 go build -a -installsuffix cgo -o client -ldflags="-s -w" cmd/client/main.go

FROM alpine:latest
RUN apk --no-cache add ca-certificates
WORKDIR /
COPY --from=base_client /app/client ./
COPY --from=base_client /app/setup.yaml ./
COPY --from=base_client /app/test_wallet ./
EXPOSE 8095

ENTRYPOINT [ "./client", "--config", "/setup.yaml" ]

