apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-exporter
  labels:
    app: node-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-exporter
  template:
    metadata:
      labels:
        app: node-exporter
    spec:
      containers:
        - name: node-exporter
          image: prom/node-exporter:latest
          args:
            - "--path.procfs=/host/proc"
            - "--path.rootfs=/rootfs"
            - "--path.sysfs=/host/sys"
            - "--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($()|/)"
          env:
            - name: GOMAXPROCS
              value: "2"
          ports:
            - containerPort: 9100
          volumeMounts:
            - mountPath: /host/proc
              name: node-exporter-0
            - mountPath: /host/sys
              name: node-exporter-1
            - mountPath: /rootfs
              name: node-exporter-2
      restartPolicy: Always
      volumes:
        - name: node-exporter-0
          emptyDir: {}
        - name: node-exporter-1
          emptyDir: {}
        - name: node-exporter-2
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: node-exporter
spec:
  selector:
    app: node-exporter
  ports:
  - protocol: "TCP"
    port: 9100
    targetPort: 9100
