global:
  scrape_interval: 1m

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 1m
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'central'
    static_configs:
      - targets: ['central-node:2112']
  
  - job_name: 'validator'
    static_configs:
      - targets: ['validator-node:2112']
  
  - job_name: 'client'
    static_configs:
      - targets: ['client-node:2112'] 
