bookkeeper:
  difficulty: 1
  block_write_timestamp: 300
  block_transactions_size: 25
server:
  port: 8080
database:
  conn_str: "mongodb://user:psswd@localhost:27017"
  database_name: "computantis"
  token: "a6858eLd1GHvoGXrq6nNhEiHrEmkRN3tXu5dYqCjiMUL9sRfUz1iBns0kEnPizzrLfj2TZGU2Wel52fJ6YDNiVrdtvf2kZm4"
  token_expiration: 604800
dataprovider:
  longevity: 300
validator:
  websocket: "ws://localhost:8080/ws"
  port: 9090
  wallet_path: "./path/to/wallet"
  toke: "some token from the provider"