bookkeeper:
  difficulty: 1
  block_write_timestamp: 300
  block_transactions_size: 25
server:
  port: 8080
  data_size_bytes: 15000000
database:
  conn_str: "postgres://computantis:computantis@localhost:5432"
  database_name: "computantis"
  token: "a6858eLd1GHvoGXrq6nNhEiHrEmkRN3tXu5dYqCjiMUL9sRfUz1iBns0kEnPizzrLfj2TZGU2Wel52fJ6YDNiVrdtvf2kZm4"
  token_expiration: 604800
dataprovider:
  longevity: 300
validator:
  websocket: "ws://localhost:8080/ws"
  port: 9090
  toke: "some token from the provider"
file_operator:
  wallet_path: "path/to/your/wallet"
  wallet_passwd: "passwd to your wallet"