bookkeeper:
  difficulty: 1
  block_write_timestamp: 300
  block_transactions_size: 1000
server:
  port: 8080
  data_size_bytes: 15000000
  websocket_address: "ws://localhost:8080/ws"
database:
  conn_str: "postgres://computantis:computantis@localhost:5432"
  database_name: "computantis"
  is_ssl: false
dataprovider:
  longevity: 300
validator:
  websocket: "ws://localhost:8080/ws"
  port: 9090
  toke: "some token from the provider"
file_operator:
  wallet_path: "path/to/your/wallet"
  wallet_passwd: "passwd to your wallet"
signer_service:
  port: 8095
  central_node_url: "http://localhost:8080"
emulator:
  timeout_seconds: 5
  tick_seconds: 5
  random: false
  signer_service_url: "http://localhost:7777"
  validator_create_hook_endpoit: "http://localhost:8090"
  port: "9999"
  issuer_wallet_public_address: "ykkeD6Tr6xikkYwC805kVoFThm8VGEHStTFk1lIU6RgEf7p3vjFpPQFI3VP9SYeARjYh2jecMSYsmgddjZZcy32iySHijJQ"
