bookkeeper:
  difficulty: 1
  block_write_timestamp: 300
  block_transactions_size: 1000
server:
  port: 8080
  data_size_bytes: 15000000
  websocket_address: "ws://localhost:8080/ws"
database:
  conn_str: "postgres://computantis:computantis@localhost:5432"
  database_name: "computantis"
dataprovider:
  longevity: 300
validator:
  websocket: "ws://localhost:8080/ws"
  port: 9090
  toke: "some token from the provider"
file_operator:
  wallet_path: "path/to/your/wallet"
  wallet_passwd: "passwd to your wallet"