apiVersion: v1
kind: Service
metadata:
  name: zincsearch
spec:
  ports:
    - port: 4080
      protocol: TCP
      targetPort: 4080
      nodePort: 30480
  selector:
    app: zincsearch
  sessionAffinity: None
  type: LoadBalancer

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zincsearch
  labels:
    name: zincsearch
spec:
  serviceName: zincsearch
  replicas: 1
  selector:
    matchLabels:
      name: zincsearch
      app: zincsearch
  template:
    metadata:
      labels:
        name: zincsearch
        app: zincsearch
    spec:
      securityContext:
        fsGroup: 2000
        runAsUser: 10000
        runAsGroup: 3000
        runAsNonRoot: true
      containers:
        - name: zincsearch
          image: public.ecr.aws/zinclabs/zincsearch:latest
          env:
            - name: ZINC_FIRST_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: secret-zinc-auth
                  key: username
            - name: ZINC_FIRST_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-zinc-auth
                  key: password
            - name: ZINC_DATA_PATH
              value: /go/bin/data
            - name: GOMAXPROCS
              value: "1"
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 1024m
              memory: 2048Mi
            requests:
              cpu: 32m
              memory: 50Mi
          ports:
            - containerPort: 4080
              name: http
          volumeMounts:
          - name: data
            mountPath: /go/bin/data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi


