// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.24.4
// source: gossip.proto

package protobufcompiled

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	GossipAPI_Alive_FullMethodName    = "/computantis.GossipAPI/Alive"
	GossipAPI_Discover_FullMethodName = "/computantis.GossipAPI/Discover"
	GossipAPI_Gossip_FullMethodName   = "/computantis.GossipAPI/Gossip"
)

// GossipAPIClient is the client API for GossipAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GossipAPIClient interface {
	Alive(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*AliveData, error)
	Discover(ctx context.Context, in *ConnectionData, opts ...grpc.CallOption) (*ConnectedNodes, error)
	Gossip(ctx context.Context, in *VertexGossip, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type gossipAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewGossipAPIClient(cc grpc.ClientConnInterface) GossipAPIClient {
	return &gossipAPIClient{cc}
}

func (c *gossipAPIClient) Alive(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*AliveData, error) {
	out := new(AliveData)
	err := c.cc.Invoke(ctx, GossipAPI_Alive_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gossipAPIClient) Discover(ctx context.Context, in *ConnectionData, opts ...grpc.CallOption) (*ConnectedNodes, error) {
	out := new(ConnectedNodes)
	err := c.cc.Invoke(ctx, GossipAPI_Discover_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gossipAPIClient) Gossip(ctx context.Context, in *VertexGossip, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, GossipAPI_Gossip_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GossipAPIServer is the server API for GossipAPI service.
// All implementations must embed UnimplementedGossipAPIServer
// for forward compatibility
type GossipAPIServer interface {
	Alive(context.Context, *emptypb.Empty) (*AliveData, error)
	Discover(context.Context, *ConnectionData) (*ConnectedNodes, error)
	Gossip(context.Context, *VertexGossip) (*emptypb.Empty, error)
	mustEmbedUnimplementedGossipAPIServer()
}

// UnimplementedGossipAPIServer must be embedded to have forward compatible implementations.
type UnimplementedGossipAPIServer struct {
}

func (UnimplementedGossipAPIServer) Alive(context.Context, *emptypb.Empty) (*AliveData, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Alive not implemented")
}
func (UnimplementedGossipAPIServer) Discover(context.Context, *ConnectionData) (*ConnectedNodes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Discover not implemented")
}
func (UnimplementedGossipAPIServer) Gossip(context.Context, *VertexGossip) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Gossip not implemented")
}
func (UnimplementedGossipAPIServer) mustEmbedUnimplementedGossipAPIServer() {}

// UnsafeGossipAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GossipAPIServer will
// result in compilation errors.
type UnsafeGossipAPIServer interface {
	mustEmbedUnimplementedGossipAPIServer()
}

func RegisterGossipAPIServer(s grpc.ServiceRegistrar, srv GossipAPIServer) {
	s.RegisterService(&GossipAPI_ServiceDesc, srv)
}

func _GossipAPI_Alive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GossipAPIServer).Alive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GossipAPI_Alive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GossipAPIServer).Alive(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _GossipAPI_Discover_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectionData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GossipAPIServer).Discover(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GossipAPI_Discover_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GossipAPIServer).Discover(ctx, req.(*ConnectionData))
	}
	return interceptor(ctx, in, info, handler)
}

func _GossipAPI_Gossip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VertexGossip)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GossipAPIServer).Gossip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GossipAPI_Gossip_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GossipAPIServer).Gossip(ctx, req.(*VertexGossip))
	}
	return interceptor(ctx, in, info, handler)
}

// GossipAPI_ServiceDesc is the grpc.ServiceDesc for GossipAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GossipAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "computantis.GossipAPI",
	HandlerType: (*GossipAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Alive",
			Handler:    _GossipAPI_Alive_Handler,
		},
		{
			MethodName: "Discover",
			Handler:    _GossipAPI_Discover_Handler,
		},
		{
			MethodName: "Gossip",
			Handler:    _GossipAPI_Gossip_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gossip.proto",
}
