// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.24.3
// source: wallet_client_api.proto

package protobufcompiled

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	WalletClientAPI_Alive_FullMethodName = "/computantis.WalletClientAPI/Alive"
)

// WalletClientAPIClient is the client API for WalletClientAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WalletClientAPIClient interface {
	Alive(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*AliveInfo, error)
}

type walletClientAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewWalletClientAPIClient(cc grpc.ClientConnInterface) WalletClientAPIClient {
	return &walletClientAPIClient{cc}
}

func (c *walletClientAPIClient) Alive(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*AliveInfo, error) {
	out := new(AliveInfo)
	err := c.cc.Invoke(ctx, WalletClientAPI_Alive_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WalletClientAPIServer is the server API for WalletClientAPI service.
// All implementations must embed UnimplementedWalletClientAPIServer
// for forward compatibility
type WalletClientAPIServer interface {
	Alive(context.Context, *emptypb.Empty) (*AliveInfo, error)
	mustEmbedUnimplementedWalletClientAPIServer()
}

// UnimplementedWalletClientAPIServer must be embedded to have forward compatible implementations.
type UnimplementedWalletClientAPIServer struct {
}

func (UnimplementedWalletClientAPIServer) Alive(context.Context, *emptypb.Empty) (*AliveInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Alive not implemented")
}
func (UnimplementedWalletClientAPIServer) mustEmbedUnimplementedWalletClientAPIServer() {}

// UnsafeWalletClientAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WalletClientAPIServer will
// result in compilation errors.
type UnsafeWalletClientAPIServer interface {
	mustEmbedUnimplementedWalletClientAPIServer()
}

func RegisterWalletClientAPIServer(s grpc.ServiceRegistrar, srv WalletClientAPIServer) {
	s.RegisterService(&WalletClientAPI_ServiceDesc, srv)
}

func _WalletClientAPI_Alive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletClientAPIServer).Alive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletClientAPI_Alive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletClientAPIServer).Alive(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// WalletClientAPI_ServiceDesc is the grpc.ServiceDesc for WalletClientAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WalletClientAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "computantis.WalletClientAPI",
	HandlerType: (*WalletClientAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Alive",
			Handler:    _WalletClientAPI_Alive_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "wallet_client_api.proto",
}
