apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  labels:
    name: prometheus-server-conf
data:
  prometheus.rules: |-
    groups:
    - name: devopscube demo alert
      rules:
      - alert: High Pod Memory
        expr: sum(container_memory_usage_bytes) > 1
        for: 1m
        labels:
          severity: slack
        annotations:
          summary: High Memory Usage
  prometheus.yml: |-
    global:
      scrape_interval: 1m
    
    scrape_configs:
      - job_name: 'prometheus'
        scrape_interval: 1m
        static_configs:
          - targets: ['localhost:9090']
    
      - job_name: 'node'
        static_configs:
          - targets: ['node-exporter:9100']
    
      - job_name: 'notary-genesis'
        static_configs:
          - targets: ['notary-node-genesis:2112']
      
      - job_name: 'notary-one'
        static_configs:
          - targets: ['notary-node-one:2112']
      
      - job_name: 'notary-two'
        static_configs:
          - targets: ['notary-node-two:2112']
      
      - job_name: 'webhooks'
        static_configs:
          - targets: ['webhooks-node:2112']
      
      - job_name: 'client'
        static_configs:
          - targets: ['client-node:2112'] 
